val rsa_modulus_bits: int	(* ℓ_n *)
val halfkey_bits: int	(* ℓ_f *)
val prime_bits: int	(* ℓ_e *)
val prime_window_bits: int	(* ℓ'_e *)
val random_bits: int	(* ℓ_v *)
val distribution_bits: int	(* ℓ_∅ *)
val hash_bits: int	(* ℓ_H *)
val reduction_bits: int	(* ℓ_r *)
val rogue_modulus_bits: int	(* ℓ_Γ *)
val rogue_security_bits: int	(* ℓ_ρ *)
val rogue_hash_bits: int	(* = ℓ_Γ+ℓ_∅ *)

val new_hash: unit -> Cryptokit.hash	(* length ℓ_H *)
val new_rogue_hash: unit -> Cryptokit.hash	(* length ℓ_Γ+ℓ_∅ *)
